### ISSUE TITLE
Erro (104, 'Connection reset by peer')

### ISSUE THREAD

**Issue by rpanah** [iclab/centinel-server#46]
Some clients can't connect to the server getting this error message:

    2015-01-20 22:49:39,208: INFO: Registering new user a03c2113-4b00-41e3-84f2-46a965226480
    2015-01-20 22:49:39,221: INFO: Starting new HTTPS connection (1): server.iclab.org
    2015-01-20 22:49:39,978: ERROR: Error trying to submit registration URL: ('Connection aborted.', error(104, 'Connection reset by peer')) 
    2015-01-20 22:49:39,979: ERROR: Unable to register: ('Connection aborted.', error(104, 'Connection reset by peer'))
    Traceback (most recent call last):
      File "/usr/local/bin/centinel-dev", line 9, in <module>
        load_entry_point('centinel-dev==0.1.5.1', 'console_scripts', 'centinel-dev')()
      File "/usr/local/lib/python2.6/dist-packages/centinel/cli.py", line 95, in run
        user = centinel.backend.User(configuration.params)
      File "/usr/local/lib/python2.6/dist-packages/centinel/backend.py", line 26, in __init__
        self.create_user()
      File "/usr/local/lib/python2.6/dist-packages/centinel/backend.py", line 229, in create_user
        raise exp
    requests.exceptions.ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

This [link](http://stackoverflow.com/questions/383738/104-connection-reset-by-peer-socket-error-or-when-does-closing-a-socket-resu) suggests a `werkzeug` (using `wsgiref`) module issue and suggests using `mod_wsgi` instead.

**Comment by rpanah** [comment]
This bug was encountered when running Centinel in Python 2.6. Upgrading to Python 2.7.x will solve the issue.
